server:
  port: 8081

spring:
  config:
    import: env.properties
hibernate:
  url: jdbc:postgresql://localhost:5432/eventpaws
  driver: org.postgresql.Driver
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  dialect: org.hibernate.dialect.PostgreSQLDialect
  showsql: true
  formatsql: true
  hbm2ddlauto: update

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000





